accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import UserProfileView, AddFollower, RemoveFollower, ListFollowers

app_name = "accounts"

urlpatterns = [
    path('<username>/', UserProfileView.as_view(), name="profile"),

    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name="add-follower"),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name="remove-follower"),

    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name="followers-list"),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('accounts.urls', namespace="users")),
    path('social/', include('social.urls', namespace="social")),

    path('', HomeView.as_view(), name="home"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/sidebars/left/items.html
{% load static %}

{% if user.is_authenticated  %}
<ul class="p-4">
    <li>
        <a href="{% url 'users:profile' user.username %}" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
            <img src="{{user.profile.picture.url}}" alt="Profile picture" class="w-10 h-10 rounded-full">
            <span class="font-semibold">{{user.username}}</span>
        </a>
    </li>
    <li>
        <a href="#" class="flex items-center space-x-2 p-2 hover:bg-gray-200 rounded-lg transition-all dark:text-dark-txt dark:hover:bg-dark-third">
            <i class='bx bx-group text-gray-500' ></i>            
            <span class="font-semibold">Friends</span>
        </a>
    </li>
    <li class="border-b border-gray-200 dark:border-dark-third mt-6"></li>
</ul>
{% endif %}

templates/components/sidebars/left/sidebar.html
{% load static %}

{% include "components/sidebars/left/items.html" %}
{% include "components/footer.html" %}